export const DEMO_CLINIC = {
  name: 'Ikeja Primary Health Centre',
  lga: 'Ikeja',
  state: 'Lagos',
  contactPhone: '+2348012345678',
} as const;

export const DEMO_CHWS = [
  {
    fullName: 'Chidi Okonkwo',
    phone: '+2348021112233',
    villageArea: 'Ikeja Central',
    status: 'active' as const,
  },
  {
    fullName: 'Blessing Adeyemi',
    phone: '+2348034445566',
    villageArea: 'Agege East',
    status: 'active' as const,
  },
  {
    fullName: 'Michael Eze',
    phone: '+2348057778899',
    villageArea: 'Ogba',
    status: 'active' as const,
  },
] as const;

export const DEMO_PATIENTS = [
  {
    key: 'amina',
    chwIndex: 0,
    fullName: 'Amina Okafor',
    phone: '+2348061122334',
    age: 28,
    village: 'Ikeja Central',
    lmp: '2026-01-10',
    edd: '2026-10-17',
    gestationalWeeks: 25,
    gravida: 2,
    parity: 1,
    riskLevel: 'low' as const,
    status: 'active' as const,
  },
  {
    key: 'fatima',
    chwIndex: 0,
    fullName: 'Fatima Bello',
    phone: '+2348072233445',
    age: 32,
    village: 'Ikeja Central',
    lmp: '2025-12-05',
    edd: '2026-09-11',
    gestationalWeeks: 30,
    gravida: 4,
    parity: 3,
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
  {
    key: 'grace',
    chwIndex: 1,
    fullName: 'Grace Emeka',
    phone: '+2348083344556',
    age: 26,
    village: 'Agege East',
    lmp: '2026-02-20',
    edd: '2026-11-27',
    gestationalWeeks: 19,
    gravida: 1,
    parity: 0,
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    key: 'halima',
    chwIndex: 1,
    fullName: 'Halima Yusuf',
    phone: '+2348094455667',
    age: 24,
    village: 'Agege East',
    lmp: '2026-03-01',
    edd: '2026-12-06',
    gestationalWeeks: 18,
    gravida: 1,
    parity: 0,
    riskLevel: 'low' as const,
    status: 'active' as const,
  },
  {
    key: 'ngozi',
    chwIndex: 2,
    fullName: 'Ngozi Obi',
    phone: '+2348105566778',
    age: 30,
    village: 'Ogba',
    lmp: '2025-11-15',
    edd: '2026-08-22',
    gestationalWeeks: 33,
    gravida: 3,
    parity: 2,
    riskLevel: 'medium' as const,
    status: 'active' as const,
  },
  {
    key: 'zainab',
    chwIndex: 2,
    fullName: 'Zainab Ibrahim',
    phone: '+2348116677889',
    age: 35,
    village: 'Ogba',
    lmp: '2025-10-20',
    edd: '2026-07-27',
    gestationalWeeks: 37,
    gravida: 5,
    parity: 4,
    riskLevel: 'high' as const,
    status: 'active' as const,
  },
] as const;

export const DEMO_VISITS = [
  {
    patientKey: 'amina',
    contactNumber: 1,
    scheduledDate: '2026-07-04',
    status: 'scheduled' as const,
    dangerSignsPresent: false,
    notes: 'Routine antenatal check scheduled for today.',
  },
  {
    patientKey: 'fatima',
    contactNumber: 1,
    scheduledDate: '2026-07-02',
    completedDate: '2026-07-02',
    bpSystolic: 158,
    bpDiastolic: 98,
    weightKg: 74,
    fundalHeightCm: 30,
    fetalHeartRate: '142',
    status: 'completed' as const,
    dangerSignsPresent: true,
    notes: 'Elevated blood pressure recorded during home visit.',
  },
  {
    patientKey: 'grace',
    contactNumber: 1,
    scheduledDate: '2026-07-03',
    completedDate: '2026-07-03',
    bpSystolic: 118,
    bpDiastolic: 76,
    weightKg: 68,
    fundalHeightCm: 19,
    fetalHeartRate: '148',
    status: 'completed' as const,
    dangerSignsPresent: false,
    notes: 'Visit completed and synced from the field.',
  },
  {
    patientKey: 'ngozi',
    contactNumber: 1,
    scheduledDate: '2026-07-01',
    status: 'missed' as const,
    dangerSignsPresent: false,
    notes: 'Patient was unavailable at home.',
  },
  {
    patientKey: 'zainab',
    contactNumber: 1,
    scheduledDate: '2026-07-05',
    status: 'scheduled' as const,
    dangerSignsPresent: false,
    notes: 'Late pregnancy follow-up scheduled.',
  },
] as const;

export const DEMO_RISK_FLAGS = [
  {
    patientKey: 'fatima',
    visitPatientKey: 'fatima',
    flagType: 'high_bp' as const,
    severity: 'high' as const,
    description: 'BP 158/98 mmHg during antenatal visit.',
    status: 'open' as const,
  },
  {
    patientKey: 'zainab',
    flagType: 'missed_visit' as const,
    severity: 'medium' as const,
    description: 'Previous visit rescheduled twice.',
    status: 'acknowledged' as const,
  },
  {
    patientKey: 'grace',
    visitPatientKey: 'grace',
    flagType: 'swelling' as const,
    severity: 'low' as const,
    description: 'Mild ankle swelling reported, resolved after rest.',
    status: 'resolved' as const,
    resolutionNotes: 'Symptoms improved; continue monitoring.',
  },
] as const;

export const DEMO_SMS_LOGS = [
  {
    patientKey: 'amina',
    visitPatientKey: 'amina',
    messageType: 'appointment_reminder' as const,
    messageBody:
      'Reminder: Your antenatal visit is scheduled for today. Reply if you need to reschedule.',
    deliveryStatus: 'delivered' as const,
    africasTalkingId: 'ATXid_demo_amina_001',
  },
  {
    patientKey: 'fatima',
    visitPatientKey: 'fatima',
    messageType: 'risk_alert' as const,
    messageBody:
      'Your recent blood pressure reading was high. Please visit the clinic as soon as possible.',
    deliveryStatus: 'sent' as const,
    africasTalkingId: 'ATXid_demo_fatima_001',
  },
  {
    patientKey: 'ngozi',
    messageType: 'followup' as const,
    messageBody:
      'We missed you at your last antenatal visit. Please contact your CHW to reschedule.',
    deliveryStatus: 'queued' as const,
  },
] as const;

export const DEMO_DATA_MARKER = 'mamatrack-demo-v1';
